spin_manifest_version = 2

[application]
name = "aes"
version = "0.1.0"
authors = ["Abdul Monum <abdulmonum@gmail.com>"]
description = "aes function adopted from wasm-orhestration"

[[trigger.http]]
route = "/aes"
component = "aes"

[component.aes]
source = "main.wasm"
allowed_outbound_hosts = []
[component.aes.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
