spin_manifest_version = 2

[application]
name = "testing"
version = "0.1.0"
authors = ["Abdul Monum <abdulmonum@gmail.com>"]
description = "testing"

[[trigger.http]]
route = "/testing"
component = "testing"

[component.testing]
source = "target/wasm32-wasi/release/testing.wasm"
allowed_outbound_hosts = []
[component.testing.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
